### PR TITLE
Suggest fix to potential typo

### PR DESCRIPTION
**Pull request by katrinleinweber**
## Description
See diff ;-)

## Related Issue
Was introduced by https://github.com/ropensci/pangaear/commit/d087bb3029991bf2c838014bfceab61519f2c1ae#diff-372451a8e6978b77b8eb118a3c15d096R14

### CODE REVIEW

**Comment by sckott** [comment]
thanks much @katrinleinweber

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Comment by katrinleinweber** [comment]
I should add: I'll be using this package as a [positive example in a lesson about re-using FAIR datasets and software](https://github.com/TIBHannover/2018-07-09-FAIR-Data-and-Software/pull/1/files#diff-bf91a0076b0f194e734f71d9aa9498ef) :-) So, an additional big thank you for having built and published this!

**Comment by sckott** [comment]
awesome, thanks for letting me know!

**Pull request merged**
